-- Seed script for Charstine Hotel Resort inventory items
-- This script adds all kitchen and restaurant inventory items

INSERT INTO items (id, name, category, quantity, description) VALUES
  -- Kitchen Inventory Items
  (1, 'Large white plastic plates', 'Kitchen Inventory', 35, 'Large serving plastic plates'),
  (2, 'Plastic plates', 'Kitchen Inventory', 109, 'Standard plastic plates'),
  (3, 'Aluminium plates', 'Kitchen Inventory', 50, 'Metal plates'),
  (4, 'Plastic cups', 'Kitchen Inventory', 133, 'Drinking plastic cups'),
  (5, 'Jugs', 'Kitchen Inventory', 2, 'Water serving jugs'),
  (6, 'Aluminium jug', 'Kitchen Inventory', 1, 'Metal water jug'),
  (7, 'Sufurias', 'Kitchen Inventory', 25, 'Cooking pots'),
  (8, 'Filters', 'Kitchen Inventory', 4, 'Liquid filtering tools'),
  (9, 'Plastic spoons', 'Kitchen Inventory', 59, 'Plastic serving spoons'),
  (10, 'Aluminium spoons', 'Kitchen Inventory', 127, 'Metal spoons'),
  (11, 'Serving spoons', 'Kitchen Inventory', 9, 'Food serving spoons'),
  (12, 'Thong', 'Kitchen Inventory', 4, 'Food handling tongs'),
  (13, 'Thermos', 'Kitchen Inventory', 3, 'Heat retaining containers'),
  (14, 'Washing hand tank', 'Kitchen Inventory', 1, 'Hand washing tank'),
  (15, 'Buckets', 'Kitchen Inventory', 15, 'Water buckets'),
  (16, 'Sina', 'Kitchen Inventory', 4, 'Storage container'),
  (17, 'Catering savers (big)', 'Kitchen Inventory', 13, 'Large food storage containers'),
  (18, 'Catering savers (small)', 'Kitchen Inventory', 7, 'Small food storage containers'),
  (19, 'Karai', 'Kitchen Inventory', 3, 'Cooking frying pan'),
  (20, 'Hotpot', 'Kitchen Inventory', 2, 'Food heat containers'),
  (21, 'Pan', 'Kitchen Inventory', 4, 'Cooking pan'),
  (22, 'Roller', 'Kitchen Inventory', 4, 'Dough rolling pin'),
  (23, 'Chopping board', 'Kitchen Inventory', 4, 'Cutting board'),
  (24, 'Chapati rolling board', 'Kitchen Inventory', 4, 'Chapati preparation board'),
  (25, 'Bowls', 'Kitchen Inventory', 25, 'Food serving bowls'),
  (26, 'Melamine cups', 'Kitchen Inventory', 23, 'Hard plastic cups'),
  (27, 'Small melamine cups', 'Kitchen Inventory', 26, 'Small hard plastic cups'),
  (28, 'Saucers', 'Kitchen Inventory', 6, 'Cup saucers'),
  (29, 'Side plates', 'Kitchen Inventory', 38, 'Small plates'),
  (30, 'Aluminium portion plates', 'Kitchen Inventory', 20, 'Metal portion plates'),
  (31, 'Hard melamine plates', 'Kitchen Inventory', 34, 'Durable melamine plates'),
  (32, 'Pilipili bowls', 'Kitchen Inventory', 3, 'Small chili bowls'),
  (33, 'Fish plates', 'Kitchen Inventory', 3, 'Plates for fish serving'),
  (34, 'Portion plates', 'Kitchen Inventory', 5, 'Food portion plates'),
  (35, 'Knives', 'Kitchen Inventory', 6, 'Cutting knives'),
  (36, 'Big bowls', 'Kitchen Inventory', 2, 'Large bowls'),
  (37, 'Kamata', 'Kitchen Inventory', 2, 'Food handling utensil'),
  (38, 'Scouping spoon', 'Kitchen Inventory', 1, 'Large scooping spoon'),
  
  -- Restaurant Inventory Items
  (39, 'Pilipili bowls', 'Restaurant Inventory', 5, 'Chili serving bowls'),
  (40, 'Cups', 'Restaurant Inventory', 11, 'Drinking cups'),
  (41, 'Saucers', 'Restaurant Inventory', 8, 'Cup saucers'),
  (42, 'Jugs', 'Restaurant Inventory', 3, 'Serving jugs'),
  (43, 'Spoons', 'Restaurant Inventory', 130, 'Eating spoons'),
  (44, 'Forks', 'Restaurant Inventory', 39, 'Eating forks'),
  (45, 'Eating knives', 'Restaurant Inventory', 11, 'Table knives'),
  (46, 'Gold spoons', 'Restaurant Inventory', 12, 'Premium spoons'),
  (47, 'Small tea spoons', 'Restaurant Inventory', 6, 'Small stirring spoons'),
  (48, 'Teaspoons', 'Restaurant Inventory', 8, 'Tea stirring spoons'),
  (49, 'Grater', 'Restaurant Inventory', 1, 'Food grating tool'),
  (50, 'Sugar dish (small)', 'Restaurant Inventory', 4, 'Small sugar container'),
  (51, 'Sugar dish (big)', 'Restaurant Inventory', 2, 'Large sugar container'),
  (52, 'Tea pots', 'Restaurant Inventory', 9, 'Tea serving pots'),
  (53, 'Trays', 'Restaurant Inventory', 4, 'Serving trays'),
  (54, 'Glasses (big)', 'Restaurant Inventory', 2, 'Large drinking glasses'),
  (55, 'Glasses (small)', 'Restaurant Inventory', 8, 'Small drinking glasses'),
  (56, 'Wine glasses', 'Restaurant Inventory', 2, 'Wine serving glasses'),
  (57, 'Kamata', 'Restaurant Inventory', 1, 'Food handling utensil')
ON CONFLICT (id) DO NOTHING;

-- Update the sequence to the highest ID
SELECT setval('items_id_seq', (SELECT MAX(id) FROM items));
